
version: 0.2
env:
  shell: /bin/bash
  variables:
    USE_EPOCH: 1
    PUBLIC_REGISTRY: public.ecr.aws/ews-network/
    DOCKER_CLI_EXPERIMENTAL: enabled
    RUNTIME_NAME: amazoncorretto

batch:
  fast-fail: true
  build-graph:
    - identifier: amd64
      env:
        compute-type: BUILD_GENERAL1_LARGE
        privileged-mode: true
        variables:
          ARCH: amd64
      buildspec: .aws/buildspec.yaml

    - identifier: arm64v8
      env:
        type: ARM_CONTAINER
        image: aws/codebuild/amazonlinux2-aarch64-standard:2.0
        compute-type: BUILD_GENERAL1_LARGE
        privileged-mode: true
        variables:
          ARCH: arm64v8
      buildspec: .aws/buildspec.yaml

    - identifier: manifest
      env:
        compute-type: BUILD_GENERAL1_LARGE
        privileged-mode: true
      depend-on:
        - amd64
        - arm64v8

phases:
  install:
    commands:
      - if [ -z ${AWS_ACCOUNT_ID+x} ]; then AWS_ACCOUNT_ID=$(aws sts get-caller-identity | jq -r .Account); fi
      - REGISTRY_URI=${AWS_ACCOUNT_ID}.dkr.ecr.${AWS_REGION:-$AWS_DEFAULT_REGION}.amazonaws.com/
      - aws ecr get-login-password --region $AWS_REGION | docker login --username AWS --password-stdin ${REGISTRY_URI}
      - aws ecr-public get-login-password --region us-east-1 | docker login --username AWS --password-stdin ${PUBLIC_REGISTRY}

  pre_build:
    commands:
      - EPOCH=`date +'%Y%m%d'`
      - SUFFIX=${COMMIT_HASH:=$EPOCH}
      - if [ $USE_EPOCH -eq 1 ]; then SUFFIX=$EPOCH; fi
      - |
          if ! [ -z "${CODEBUILD_WEBHOOK_TRIGGER+x}" ]; then
            echo TRIGGER is $CODEBUILD_WEBHOOK_TRIGGER
            PRE=`echo $CODEBUILD_WEBHOOK_TRIGGER|cut -d '/' -f 1`;
            echo PRE is $PRE
            echo SUFFIX is $SUFFIX
            if [ "${PRE}" == "tag" ]; then SUFFIX=`echo $CODEBUILD_WEBHOOK_TRIGGER|cut -d '/' -f 2`; TAG_RELEASE=1 ; fi
          fi
      - echo SUFFIX ends up being $SUFFIX

  build:
    commands:
      - docker pull ${PUBLIC_REGISTRY}akhq:${SUFFIX}-amd64
      - docker pull ${PUBLIC_REGISTRY}akhq:${SUFFIX}-arm64v8
      - |
          docker manifest create ${PUBLIC_REGISTRY}akhq:${SUFFIX} \
            --amend ${PUBLIC_REGISTRY}akhq:${SUFFIX}-amd64
            --amend ${PUBLIC_REGISTRY}akhq:${SUFFIX}-arm64v8
      - docker manifest push PUBLIC_REGISTRYakhq${SUFFIX}

    finally:
      - rm -rfv ~/.docker
